const String CHANNEL_NAME_TELEPHONY = 'com.masqt.diziet/telephony';

const String MESSAGE_TYPE_CONNECTION_FAILURE = 'MESSAGE_TYPE_CONNECTION_FAILURE';
const String MESSAGE_TYPE_INBOUND_SMS = 'MESSAGE_TYPE_INBOUND_SMS';
const String MESSAGE_TYPE_INCOMING_CALL_INVITE =
    'MESSAGE_TYPE_INCOMING_CALL_INVITE';
const String MESSAGE_TYPE_INCOMING_CALL_INVITE_CANCELLED =
  'MESSAGE_TYPE_INCOMING_CALL_INVITE_CANCELLED';
